### ISSUE TITLE
Could not pass event PlayerDeathEvent

### ISSUE THREAD

**Issue by yunusalbayrak** [Bryan-Correll/ServerLog#1]
Mc version: 1.11.2
https://pastebin.com/VjNtpnkL

**Comment by DelKatey** [comment]
Having the same issue on MC Spigot version 1.13.2.

https://paste.helpch.at/juwohetohu.cs

**Comment by ProPhaze** [comment]
@DelKatey @Tanimsiz 

Thank you both so much for making me aware of this problem. The latest version supports all Spigot updates and the problem you were both having has been sorted!
