### ISSUE TITLE
1.14 Support?

### ISSUE THREAD

**Issue by Kobe024** [Bryan-Correll/ServerLog#2]
Hi, this seems like an awesome plugin to have, unfortunately it's not working in 1.14.4.

Are there any plans to update it for 1.14? I know I'm not the only one who would want this.

Thanks for making the plugin in the first place though :D

**Comment by Pr0boszcz91** [comment]
Would also like this to be updated for 1.14.4 since currently it's throwing an error everytime a player sends a chat message and it's not being saved in the logs.
![log](https://user-images.githubusercontent.com/42723406/68543153-b3df3300-03b3-11ea-9ba8-dfaf951d7be2.PNG)

**Comment by ProPhaze** [comment]
This issue has since been fixed in the latest update. Thank you guys for letting us know!
